### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by sschepens** [zhaofeng0019/nginx-upstream-dynamic-resolve-servers#2]
Hi,
We're using dynamic_resolve directive from tengine, but are analyzing other options, since that directive resolves DNS in the request path and it should be better to have it asynchronously update, not blocking any request.

I have some questions regarding this module:
- Why is ssl session resumption disabled, when tengine's directive has it enabled?
- According to [this](https://github.com/zhaofeng0019/nginx-upstream-dynamic-resolve-servers/blob/master/ngx_http_upstream_dynamic_resolve_servers.c#L230) if dns has just refreshed and a request is being processed the request would be failed, is that correct? Isn't there a high chance of this happening if you have a lot of traffic and DNS refresh quickly (60s)?
- Is there any way this module is different that tengine's?

**Comment by zhaofeng0019** [comment]
1.Why is ssl session resumption disabled, when tengine's directive has it enabled?
   because when use ssl session resumption we always use shared memory to save the session, and this may cause memory problem when dns refresh (it may refresh the configure)
2. According to this if dns has just refreshed and a request is being processed the request would be failed, is that correct? Isn't there a high chance of this happening if you have a lot of traffic and DNS refresh quickly (60s)?
   not what you think about. this describes this scene: when you open try next option, and request one backend fail then you would try another backend and at this time,the dns refresed, so you can not try another backend because at this time,it may changed.
3.Is there any way this module is different that tengine's?
as you say,  it asynchronously update, not blocking any request. and  it's flexible

**Comment by sschepens** [comment]
@zhaofeng0019 thanks for replying.

Regarding the first point, isn't there, a risk in tengine's own implementation of session resumption? or is it somehow handling it differently?
On the other hand, isn't there a way to fix it? to know when the dns has refreshed or know when the session should be released?

Regarding the second point, so this only happens when nginx retries a request due to a failed backend, right?

Thanks!

**Comment by zhaofeng0019** [comment]
as far as i know tengine may do it another way,because it not need to be compatible to original nginx.
in the module i can't fix it because it just a third-party module and can't change the structure of nginx.
about the second point, you're right, this only happens when nginx retries a request due to a failed backend and the dns changed during this

**Comment by sschepens** [comment]
@zhaofeng0019 i have one more question, what happens to existing connections to backends if the DNS refreshes and does not include them? We have cases with big ELBs in AWS in which Route53 only returns a subset of the IPs in the DNS lookup, so everytime you query DNS you could have a different set of nodes.

**Comment by zhaofeng0019** [comment]
if the DNS refreshes and does not include one host, the configure will also be refreshed, so the connection may failed.

**Comment by wyzc2** [comment]
Hi @zhaofeng0019, I also have some questions if you don't mind.

* What Nginx version(s) is this module compatible with?
* Has this module been run and tested in any production environment?

Thanks!

**Comment by zhaofeng0019** [comment]
> Hi @zhaofeng0019, I also have some questions if you don't mind.
> 
> * What Nginx version(s) is this module compatible with?
> * Has this module been run and tested in any production environment?
> 
> Thanks!

1. nginx 1.6, 1.7, 1.8, 1.9
2. if you just want dynamic dns without keepalive upstream i recommend **GUI/nginx-upstream-dynamic-servers** , it has been tesetd in the production environment, and my job is to fix some bug and not tested in production environment.

**Comment by ArighnaIITG** [comment]
Hi @zhaofeng0019 , I have some questions -

1. I want a dynamic dns module, which is compatible with upstream check module. Can you tell me if tengine's upstream check module can be used with this, since that version of check module contains dynamic peer adding functions, which is not there in the upstream check module in github? Have you ever tested GUI/nginx-upstream-dynamic-servers with tengine's check module to see if it works, and not leads to seg faults?

2. Also, does GUI/nginx-upstream-dynamic-servers asynchronously update the resolved IP list?

3. I see that GUI/nginx-upstream-dynamic-servers do not start if FQDN doesn't resolve to an IP, and I believe that your fork removes this obstruction. Could you tell me the difference, or provide me with a patch that resolves this issue? Would be highly appreciated.

**Comment by zhaofeng0019** [comment]
here is my answer to ArighnaIITG
1. actually neither GUI/nginx-upstream-dynamic-servers or my modules can not be compatible with tengine's upstream check module because there are some memory dynamic alloced and freeed and upstream check module may use them, if you want to use that, you may modify  upstream check module also.
2. yes
3. at first  GUI/nginx-upstream-dynamic-servers will enter the original process -- it will resolve the domain by the dns server in  /etc/resolv.conf and not your dns sever in resolver directive and this process may blocked and will take a long time (very long maybe minutes), so i skip this process at first because it will asynchronously  resolve the domain anyway you can see comment in my code [this way](https://github.com/zhaofeng0019/nginx-upstream-dynamic-resolve-servers/blob/9ad9322e99fa9f07fb3dc1cbdef355d1ae81f376/ngx_http_upstream_dynamic_resolve_servers.c#L275)
